# Site settings
title: "HappyHacker.de"
subtitle: "Wie du ein glücklicher Programmier werden kannst"
email: rike@loewe.io
description: "Ein glücklicher Software-Entwickler zu sein ist kein Schicksal. Es ist eine aktive Entscheidung und dann eine Reihe neuer Gewohnheiten. Lass dich inspirieren und finde heraus, wie es geht auf HappyHacker.de"
baseurl: ""
url: "http://happyhacker.de"

# Build settings
markdown: kramdown
permalink: pretty
